leptos-rs/cargo-leptos

- src/run/new.rs
- Link to download `cargo-generate` binaries had incorrect URL
- This caused an issue when `cargo-generate` was not installed in PATH (via `cargo install cargo-generate)`
- Arguments for `cargo-generate` 
- Missing `generate` argument (it's also needed when invoking the command from PATH `~/.cargo/bin/cargo-generate generate`)
- `--name test` should be send to  `["--name", "test"]`
> Fix `cargo-generate` arguments and binary URL

- Cargo.lock
- Cargo.toml
This is a temporary fix as it is probably not a good idea to track the main branch. But I assume it will be fixed shortly? In any case this makes cargo-leptos work on my machine.
> use git dependency

- Cargo.lock
- Cargo.toml
- src/ext/exe.rs
- src/ext/mod.rs
- src/main.rs
- src/run/new.rs
- src/run/sass.rs
- src/run/wasm.rs
Intial implementation.
I've tested it on Windows 11 only (no macOS and Linux yet). But I'm fairly confident it will work fine.
I found a new crate [`decompress`](https://github.com/rusty-ferris-club/decompress) for extracting archives. I struggled to find any other good alternative.
In works fine but I'm not happy with the code yet.
Hopefully in couple of days the PR will be ready.
Any feedback is appriciated!
> `binary-install` replacement, resolves #24

- src/config/bin_package.rs
- src/config/lib_package.rs
- src/config/snapshots/cargo_leptos__config__tests__project.snap
In src/config/bin_package.rs and in src/config/lib_package.rs
Calling `rel_dir.join("src")` was appending:
`.\\src` on Windows
`./src` on Linux
The rest of the parsed folders are formatted without the leading ./ or .\\\\ leading to nothing ever being a "watched" item.
Changing the join to match how other directories are parsed gives:
`rel_dir.join("src").unbase(&rel_dir).expect()`
> Fix for single-package setup not triggering rebuild on edits

- src/ext/mod.rs
- src/ext/path.rs
- src/service/serve.rs
- solves issues on some platforms where running binaries cannot be edited
- since the binary is copied we need to copy possible debugging files to match
> copy server executable to new location before running it

- src/config/bin_package.rs
- src/config/lib_package.rs
Hi,
for `lib-features` and `bin-features`, README says the config  `Can be over-ridden with the command line parameter`.
But running `cargo leptos build --lib-features hydrate,banana --bin-features ssr,apple` on the `start` project compiles fine, while I would expect it to fail because banana and apple are not registered features.
Here is a quick fix, which successfully fail for non-existent features:
```
╰─>$ cargo leptos build --lib-features hydrate,banana --bin-features ssr,apple
error: none of the selected packages contains these features: banana
error: none of the selected packages contains these features: apple
```
> Fix precedence between config and cli for {bin,lib}-features

- README.md
- src/compile/tests.rs
- src/config/bin_package.rs
- src/config/cli.rs
- src/config/lib_package.rs
- src/config/project.rs
- src/config/snapshots/cargo_leptos__config__tests__project.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_in_subdir_project2.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_project1.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_project2.snap
- src/config/tests.rs
Hi,
This PR add a `--feature` flag to enable features on all build, and shortcut
`cargo leptos watch --lib-features hydrate,banana --bin-features ssr,banana` into 
`cargo leptos watch --features banana`.
> Add `--features` flag

- Cargo.toml
- README.md
- src/ext/exe.rs
To better support Nix, it's good to not download anything during initialization or setup, and let Nix handle any additional deps. This PR throws an error if cargo leptos is built with the no_downloads feature and it needs something.
> Add feature to prevent downloading dependencies

- Cargo.lock
- Cargo.toml
- README.md
- src/ext/exe.rs
- src/ext/tests.rs
Refactor Exe and make cache dir optional for users building with a `no_downloads` feature 
Replaces #80
> Refactor Exe

- .github/workflows/release.yml
- Cargo.toml
This PR uses cargo-dist to generate binaries in a github release **when a tag is pushed to github**.
These binaries are compatible with [cargo-binstall](https://github.com/cargo-bins/cargo-binstall) as well.
The action is generated from `cargo dist init --ci=github` and unmodified from that output. Future updates should be as easy as running this init command again to pull in cargo-dist updates.
cargo-dist recently got a bunch of documentation in the form of a book if you want to know more about what it's doing: https://opensource.axo.dev/cargo-dist/book/ and I've produced a video showing what the results should look like using one of my own projects as an example. https://youtu.be/Cl2qgOwswH4
closes #84
> use cargo-dist to release binaries

- src/compile/server.rs
Changes arguments passed to `cargo test` so that all server test targets are executed.
Resolves https://github.com/leptos-rs/cargo-leptos/issues/66
@akesson This PR depends on an upstream fix in the leptos crate. This is required to resolve an issue with doctests and server functions. Suggest this PR is not released until leptos 0.1.4 is available.
> Fix server testing.

- src/service/reload.rs
Fix #101
Once iter_intersperse is stabilised, that might be a nicer way to write it.
> Always use `/` as separator in css links

- src/command/new.rs
Ran into this just now:
```
shell ❯ cargo leptos new --git https://github.com/Gentle/start-axum-workspace
Error: Could not spawn command at `/home/k/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.1.8/src/command/new.rs:61:14`
Caused by:
No such file or directory (os error 2)
```
> Show a better error if cargo-generate does not exist

- Cargo.lock
- Cargo.toml
- examples/project/Cargo.lock
- examples/project/Cargo.toml
- examples/workspace/Cargo.lock
- examples/workspace/Cargo.toml
- examples/workspace/project2/Cargo.toml
- src/ext/cargo.rs
- src/snapshots/cargo_leptos__tests__workspace_build.snap
This should solve issues when not specifying the wasm_bindgen locked version to =0.2.84.
> Updated wasm_bindgen to 0.2.85

- README.md
- examples/workspace/Cargo.toml
- examples/workspace/project2/Cargo.toml
Also add missing `--locked` to custom install command in README.
(see [discord](https://discord.com/channels/1031524867910148188/1040262908074000425/1103770256738107443) for why). 
I think this is a dupe, but more thorough implementation of #119.
> [docs] Change `akesson` to `leptos-rs` in Github URLs

- src/ext/exe.rs
- src/ext/util.rs
`dart-sass` is incompatible with MUSL-based Linux, only supporting the standard GNU/glibc version. However there are other third party alternatives which can be used, such as [`dart-musl`][dart-musl].
To accommodate this, if the MUSL `target_env` is found, the SASS download URL is changed to that of the appropriate [`dart-musl`][dart-musl] binary, based on the architecture for which the app is compiled.
[dart-musl]: https://github.com/dart-musl/dart-sass
Closes: #144
> feat(dart-musl): download proper dart-sass for musl

- src/compile/style.rs
- src/config/bin_package.rs
- src/config/end2end.rs
- src/config/lib_package.rs
- src/config/mod.rs
- src/config/profile.rs
- src/config/project.rs
- src/ext/cargo.rs
- src/ext/exe.rs
- src/ext/fs.rs
- src/ext/path.rs
- src/service/notify.rs
- src/service/site.rs
I am think about starting an issue here..
While I read the code, and get my bearings
it is my habit to run
Cargo clippy
Cargo outdated
Cargo machete
This maybe the first of a few PRs..
"I Ran cargo clippy --fix "
and then reviewed all the changes..
It took me a little time to justify this change
but I see no change in functionality.
```
-    metadata.as_object().map(|o| o.get("leptos")).flatten()
+    metadata.as_object().and_then(|o| o.get("leptos"))
```
Also few .clone() call have been removed which is always nice to see.
> Chore: Clippy fixes

- src/command/watch.rs
- src/ext/cargo.rs
Addresses #108. At present, if any lib/bin files are touched, the build process waits for style, lib, and bin all to be rebuilt before sending a reload signal, even though it *could* send the style reload signal separately, as this is usually a faster process (Tailwind vs. rustc). 
> Note: This isn't as relevant with plain CSS or with SASS, because in those cases only CSS files are touched and not Rust, so lib/bin aren't recompiled. 
I made this small change to spawn the style rebuild separately rather than joining it with the Rust rebuild.
~However, it only works once, i.e., on first file save. I assume this is because the compilation process that's running in this loop isn't interrupted and stopped if I make another file edit, but I'm not sure. I'm pretty weak on Tokio/concurrent stuff …
> Run style rebuilds separately

- src/service/serve.rs
Started a new project with `cargo leptos new --git leptos-rs/start` had to guess it was at port 3000. This adds a message to the bottom of the startup output:
No worries if this isn't wanted/needed or if it's implemented in a non-ideal way. Feel free to delete the PR or lemme know how to make it better!
> Show where the app is served on startup

- .gitignore
- Cargo.lock
- Cargo.toml
- src/command/watch.rs
- src/compile/front.rs
- src/compile/style.rs
- src/compile/tailwind.rs
- src/config/dotenvs.rs
- src/config/end2end.rs
- src/ext/exe.rs
- src/ext/tests.rs
- src/main.rs
- src/service/reload.rs
Reworked the command subsystem. Commands are now implemented as traits with default
template methods and just need to fill out the customized parts (vs duplicating most of the code).
Improved the user feedback, made the output consistent across commands.
Fixed error handling so any download and binary executable resolution problems are exposed (vs being silently swallowed).
* `cargo leptos` will now check (once a day) for new versions of tools like `sass`,
`tailwindcss`, `wasm-ops` via the GitHub release API and inform the user of a newer available version. This happens lazily
for commands when they are used, but only once on startup and no more frequently than once a day.
* As part of the above exercise, improved the version recognition, so all kinds of variants like `1.0, version_112, …
> Improved commands sub-system

- .gitignore
- src/ext/path.rs
* Drop redundant clone()
* Re-order impl methods to follow the trait order.
> Cleanup - addressed linter warnings:

- src/ext/exe.rs
Added detection for Linux targets that use the musl libc on the download of the `cargo-generate` binary. The current `main` branch does not do any detection for it, only for `SASS`.
With this pull request, I managed to get cargo-leptos and leptos itself fully working on Alpine Linux.
> Fixed musl binary download for cargo-generate

- Cargo.lock
- Cargo.toml
- src/service/reload.rs
ran cargo outdated
I have trimmed down the list by using the modern versions of a couple of packges.
it a long list ... and can be completely cleared because of this
Cargo.toml
--  not using notify 5.0 because it uses Crossbeam which has an issue with tokio
notify = "4.0"
> ran Cargo outdated

- README.md
- src/config/snapshots/cargo_leptos__config__tests__project.snap
- src/config/tailwind.rs
- src/service/notify.rs
Changes to `tailwind.config.js` did not previously trigger a style rebuild (only `.rs` and `.css` files did). This watches the tailwind input and config paths specified in `Cargo.toml` and watches them for changes, rebuilding style as necessary.
Also adjusts defaults to avoid using a `./` relative path prefix as this breaks watch: https://github.com/leptos-rs/cargo-leptos/issues/99
> Watch tailwind configuration and rebuild style on change

- Cargo.lock
- Cargo.toml
> Rev up cargo-leptos dependency to the latest stable 0.4.8.

- Cargo.lock
- Cargo.toml
- src/compile/style.rs
Use target browsers in minify step.
A few months ago I ran into an issue, when compiling in release mode, where some css rules were wrongly merging together, resulting in broken css in firefox. I thought the issue was in lightningcss and [reported it there at the time](
https://github.com/parcel-bundler/lightningcss/issues/548), and now it seems the issue has been fixed on that side.
However I tested with latest lightningcss and the issue persisted, so it seemed like the only way this was happening was if the targets weren't being correctly passed in the minify step and lo and behold that was indeed what was happening. I also tried only the code change without bumping lightningcss and that was not enough to generate correct css.
With both passing targets and bumping lightningcss, the css …
> Specify browser targets in minify step

- Cargo.lock
- Cargo.toml
- README.md
- src/compile/front.rs
- src/compile/server.rs
- src/compile/tests.rs
- src/config/bin_package.rs
- src/config/lib_package.rs
- src/config/project.rs
- src/config/snapshots/cargo_leptos__config__tests__project.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_in_subdir_project2.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_project1.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_project2.snap
- src/ext/cargo.rs
Changes:
- Removes hard-coded `target/server` and `target/front`
- Using the normal target directory allows for sharing build dependencies between projects, which can significantly reduce compile times
- It is unclear why they're hardcoded separate directories in the first place
- Removing them was easier than making them use the proper target directory
- Uses proper relative paths for bin and lib packages
- Fixes a crash/panic when the configured target directory was outside the workspace directory
- Fixes #74
- Fixes #127
- Fixes #157
- Fixes #186
- Adds dependency `pathdiff`
- It can still fail, but insofar I can tell will only do so if the base path is relative and the target path is absolute
- Absolute paths would be better:
- No chance of failure
- No additional dependency
- But …
> Respect Cargo target directory configuration

- src/command/serve.rs
- src/service/serve.rs
Currently, `serve` and `watch` share an underlying server which causes `serve` to wait for ctrl+c to be pressed, even if the underlying process has gracefully exited.
This PR makes `serve` behave as a one-shot and exit if its underlying process terminates, while preserving the reload functionality of the `watch` command.
> Exit serve command if child process exits

- README.md
The readme incorrectly describes how to specify a debug/dev profile.
The correct way is to use the `dev` key word.
> Fix debug profile in readme

- README.md
It seems like the command was renamed at some point from `end2end` to `end-to-end`.
> Fix documentation for end-to-end command

- README.md
- examples/project/Cargo.toml
- examples/project/additionnal_files/foo.json
- src/compile/change.rs
- src/config/project.rs
- src/service/notify.rs
Add an option to watch any file:
```toml
#
watch-additional-files = ["additional_files", "custom_config.json"]
```
A change to any of those files trigger a rebuild of both client and server.
> Option to watch additional files

- Cargo.lock
- Cargo.toml
Makes cargo leptos hot-reload work with leptos 0.5 .
> Updating the cargo leptos so it works with leptos 0.5.0!

- src/lib.rs
`cargo leptos` only searches for globally installed binaries.
This PR adds a check at the startup of `cargo leptos` that detects a `package.json` file and tries to add the `<project_working_dir>/node_modules/.bin/` folder to the `PATH` environment variable.
> Add 'node_modules/.bin' folder to PATH when package.json is present

- README.md
- src/compile/front.rs
- src/config/lib_package.rs
- src/config/project.rs
`cargo leptos watch` compiles frontend and server code completely new, without using incremental compilation.
This is a bug of `cargo` or `rustc`, because changing the target from `native` to `wasm32` changes the `RUSTFLAGS` which in turn triggers a complete rebuild by cargo (see https://github.com/rust-lang/cargo/issues/8716).
This PR introduces a new option in the project settings (`separate-front-target-dir`) that instructs `cargo leptos` to change the `--target-dir` for the frontend compilation to `<project-taget-dir>/front` so that the `RUSTFLAGS` stay the same between the compilations.
> Fix incremental compilation by using separate target dir for front

- src/compile/tailwind.rs
- src/config/project.rs
- src/config/snapshots/cargo_leptos__config__tests__project.snap
- src/config/tailwind.rs
closes #136 
Let tailwind output to a temporary file and read it afterwards instead of returning the stdout of the tailwind command.
I didn't know a better way than to put the temp file into a `tmp` directory inside the `target` folder.
`temp_dir` isn't supported by serde and I didn't want to put it into the `TailwindConfig` struct.
The path is present in the output for the output of the tailwind command for better transparency with the users.
> Fix tailwind with plugins by using a temporary file

- Cargo.lock
Nix cares if the Cargo.lock is out of date, it needs to be updated when a new release goes out
> Cargo.lock needs updating

- Cargo.lock
- Cargo.toml
This should allow the failing musl build to work correctly (I hope).
> use `rustls-tls` to remove `openssl` dependency

- .gitignore
Add `.direnv` directory created by [`nix-direnv`](https://github.com/nix-community/nix-direnv) to `.gitignore`, since both direnv and nix are used in the project.
> Add `.direnv/` to `.gitignore`

- src/compile/front.rs
- src/compile/mod.rs
- src/compile/server.rs
- src/compile/tests.rs
This PR fixes passing multiple cargo args via `--bin-cargo-args` and
`--lib-cargo-args`. Previously those arguments would be merged into a
single argument containing spaces inside, leading to errors.
Discovered when trying to cross-compile in a wrong way (before figuring
out `LEPTOS_BIN_TARGET_TRIPLE`) and getting this error:
```
error: unexpected argument '--target x86_64-unknown-linux-gnu' found
tip: a similar argument exists: '--target'
```
> Fix passing multiple cargo args via `--{bin,lib}-cargo-args`

- README.md
As discussed in #224 (better late than never I hope), `bin-cargo-command` is now included in the readme.
Secondly, I noticed two other lines were mixed between snake and kebab-case. Went ahead and corrected those.
> Doc `bin-cargo-command` in `README.me`

- flake.nix
Since `insta` is used for snapshots in tests, it is convenient to have
`cargo-insta` in PATH.
> Add `cargo-insta` to dev shell in Nix flake

- src/command/build.rs
- src/compile/front.rs
This really helped me debug my issue.
Otherwise, if there's an error, the `match` on the next line returns w/o telling me the command that was run to cause the error.
> Add more debug logs.

- src/config/bin_package.rs
- src/config/project.rs
If your bin name is different then your package name you'll get a missing file error.
```rust
Error: at `/Users/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.5/src/command/serve.rs:8:46`
Caused by:
0: at `/Users/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.5/src/compile/server.rs:39:22`
1: at `/Users/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.5/src/service/site.rs:117:44`
2: Could not read "target/debug/leptos_chat_app" at `/Users/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.5/src/ext/fs.rs:44:10`
3: No such file or directory (os error 2)
```
But this pull request adds a bin-exe parameter which you can use to change the output file name.
> bin_exe override

- src/config/cli.rs
Fixes issue #247 
Tell the user to use the `-vv` flag for very verbose, instead of the incorrect `--vv`.
> Fix help message for verbosity option

- Cargo.lock
- src/compile/server.rs
- src/config/bin_package.rs
To better support Spin, I've modified cargo-leptos to be able to generate wasi lib servers (and probably wasm32-unknown-unknown) ones too
> Added the ability to compile the server to a WASM or WASI lib

- README.md
- src/config/project.rs
The change in #216 did not explain enough and contradicted the way the option was documented in the README.
See #203 and #217.
> Explain what has become of separate-front-target-dir

- Cargo.lock
- src/compile/tests.rs
- src/config/bin_package.rs
- src/config/cli.rs
- src/config/mod.rs
- src/config/project.rs
- src/config/snapshots/cargo_leptos__config__tests__workspace.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_bin_args_project2.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_in_subdir_project2.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_project2.snap
- src/config/tests.rs
- src/lib.rs
- src/service/serve.rs
For #245 
So we can pass command line arguments to bin, such as `cargo leptos watch -v -- --foo`.
> Add bin args for `watch` and `serve` commands

- src/ext/exe.rs
It looks like that version is the one that includes the aarch64 binary for linux 
https://github.com/WebAssembly/binaryen/releases/tag/version_117
> chore: update default version of wasm-opt

- src/compile/sass.rs
Fixed an output bug where Dart Sass CSS compilation would display info saying it was for Tailwind.
> Fixed Output Bug

- src/config/lib_package.rs
- src/config/project.rs
`*-cargo-args` was expected to be a `String` even tough the docs shows them as arrays.
The empty cli flag for `lib-cargo-args` no longer overrides the one provided in the config.
I have not further investigated `bin-cargo-args`.
> Fix cargo args

- README.md
- src/config/dotenvs.rs
- src/config/hash_file.rs
- src/config/project.rs
I'd appreciate a code review on this as i'm pretty new to contributing to open source rust.
1.
In Cargo.toml one can add
hash-file-name="my-hash-file.txt"
(it was erroneously checking for "hash-file" instead of "hash-file-name"). This is potentially a breaking change but shouldn't affect anyone since it was a bug to begin with?
2.
Ensure the environment variable LEPTOS_HASH_FILE_NAME is allowed.
3.
fix the directory of hash.txt when cross compiling by using the exact directory that the binary is in.
Cheers
fixes: #278
> tweaks for hash_file

- examples/workspace/Cargo.lock
- examples/workspace/Cargo.toml
- examples/workspace/project1/app/src/lib.rs
- examples/workspace/project1/front/src/lib.rs
- examples/workspace/project1/server/src/main.rs
- examples/workspace/project2/src/app/mod.rs
- examples/workspace/project2/src/lib.rs
- examples/workspace/project2/src/server/mod.rs
As of leptos 0.5 there is a major change:  the cx variable has been removed so there are lots of changes of the form below
```rustlang
-pub fn App(cx: Scope) -> impl IntoView {
-    provide_meta_context(cx);
+pub fn App() -> impl IntoView {
view! {
-        cx,
<div>
```
NB This is all part of a mini project to ship wreak  #274... break the PR into part that are easy to reivew.
> Minor: examples - Bump assorted leptos sub-modules up to version 0.6.'

- .github/workflows/test.yml
over in PR Maintenance patch #274 
I initially tried to generate a series of small upgrade patches.
but due to the messy coupling between crates many changes have to be pushed into 
a single PR 
Today I am trying to isolate a subtle bug "new tests are passing in Ubuntu - but failing on Windows" 
To reduce complexity I am re-reviewing my own work and peeling off isolated micro issues 
into isolated PRs.
This is going to be the first of many,
> Minor: actions/checkout now consistently using version 4.

- Cargo.lock
- Cargo.toml
Over in #274  I am trying to reduce the complexity of a MEGA PR 
Here I am splitting off changes to the reqwest crate to see if it unwinds a 
suble unwanted coupling between crates.
Currently is looks like the "notify" and "zip" crates are entangled in a way that makes me grumpy.
> Minor: Bump Reqwest to 0.12.

- src/compile/tailwind.rs
Small change to the CLI command used to run tailwind. I've run into a difficult to debug error that I suspect is caused by what is there before this change. Regardless, [the page on Tailwind CLI](https://tailwindcss.com/docs/installation) uses `tailwindcss` as the command as opposed to `tailwind`.
> Run tailwindcss command instead of tailwind

- Cargo.lock
- Cargo.toml
Over in #274 I am wresting with a complex coupling between crates
The way do reason with the problem is to strip off crates updates into small managable PRs 
These should be a breeze to review... and incidently reducing the complexity of the mega patch...
Here I am pairing up updated for the crates "which" and lightningcss
> Minor: Bump crate versions for which and lightningcss

- Cargo.lock
- src/compile/hash.rs
- src/compile/tests.rs
- src/config/bin_package.rs
- src/tests.rs
Just picking up clippy lints.
Lots of minor things, of most significance,  now using .flattern() where possible.
```rustlang
-            for entry in entries {
-                if let Ok(entry) = entry {
+            for entry in entries.flatten() {
```
> Minor: clippy fixes.

- Cargo.lock
- Cargo.toml
- src/compile/server.rs
- src/config/bin_package.rs
I wanted to use a different cargo command with two words in it, which does not work in cargo leptos
> Fix issue with multi word bin commands

- src/ext/cargo.rs
I'm unfamiliar with the camino crate so I'm not sure if maybe there's a more elegant way to write this.
> fix: edge case for path_dependency == workspace_root (Fixes #303)

- src/config/hash_file.rs
- src/config/project.rs
hash.txt file was being looked for at the bin exec path but lives at the workspace root level
> hash.txt path correction

- src/compile/hash.rs
Relates to #347
This makes sure that hashing works after `cargo clean`.
> create parent dir for hashfile if not exists

- src/config/hash_file.rs
- src/config/project.rs
This change should put the hashing file name issue to bed, closing #347
> Fix hashing in workspaces and single crates

- Cargo.lock
- src/command/new.rs
NB: this is a tiny change that doesn’t modify any logic, just makes leptos templates a little quicker to get up & running.
Also included a new style of short-form template instantiation for official templates, without the `leptos-rs/` prefix:
A template can now alternatively be instantiated like 
`cargo leptos new —git start-axum`, 
`cargo leptos new —git start-actix`, or 
`cargo leptos new —git start-spin`;
the old template instantiation behaviour still exists (and now exists for all templates), so eg.
`cargo leptos new —git leptos-rs/start-aws` will work as well.
> feat: implemented workaround to enable short form instantiation of all offical leptos-rs templates

- Cargo.lock
- Cargo.toml
- examples/project/Cargo.lock
- examples/project/Cargo.toml
- examples/workspace/Cargo.lock
- examples/workspace/project1/front/Cargo.toml
- examples/workspace/project2/Cargo.toml
- src/compile/front.rs
I did not bump all the modules reported by "outdated" 
There is a long standing sore #274 ... which is in limbo 
Where I am having trouble bumping "notify" -- I don't have a window build to debug the issues.
274 spawned lots of minor patches fixing unrelated issues... time moves on and this patch 
is just nibbling at the edges fixing more unrelated issues.
> Chore: Updating lots of crates

- src/compile/front.rs
Currently wasm-opt is set to compile for speed, but if we are setting a default for wasm-opt for users than I believe most people would want it optimizing for size instead.
> Change the default wasm-opt settings to optimize for size

- src/compile/hash.rs
Changes:
- Do not hash inline.js files as it will break the imports when using the webassembly in the frontend
- When hashing files, if the file is within snippets is called inline and has an extension of .js then do not hash it
> fix(Hash-376): Hash should not be applied on inline.js

- src/config/bin_package.rs
Before:
Cargo-leptos was finding .exe file after building server when cross compiling to non-windows targets which does not use .exe extensions at all.
After:
This commit fixes it to use .exe extension only when the target machine is also windows.
Error log:
Error: at `D:\a\cargo-leptos\cargo-leptos\src\compile\server.rs:40:22` Caused by:
0: at `D:\a\cargo-leptos\cargo-leptos\src\service\site.rs:117:44`
1: Could not read "target\\aarch64-unknown-linux-gnu\\wasm-release\\leptos.exe" at `D:\a\cargo-leptos\cargo-leptos\src\ext\fs.rs:44:10`
2: No such file or directory (os error 2)
> fix for non-windows target cross compile on windows

- Cargo.lock
psm@0.1.23 doesn't build for aarch64-pc-windows-gnullvm target. newer version fixed this issue
> deps: Update psm

- Cargo.lock
- Cargo.toml
Alternative fix for #419.
`cargo test` seemed fine.
> Update swc to 10.0

- examples/project/Cargo.toml
- examples/workspace/Cargo.toml
- src/compile/tests.rs
- src/config/dotenvs.rs
- src/config/project.rs
- src/config/snapshots/cargo_leptos__config__tests__workspace.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_bin_args_project2.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_in_subdir_project2.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_project1.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_project2.snap
Add support to configure and set the `SERVER_FN_PREFIX`, `DISABLE_SERVER_FN_HASH`, and `SERVER_FN_MOD_PATH` env vars using the leptos project config.
See the following PR for more info: https://github.com/leptos-rs/leptos/pull/3438
> feat: Add server function configs

- Cargo.lock
- Cargo.toml
- src/command/test.rs
- src/compile/assets.rs
- src/compile/front.rs
- src/compile/sass.rs
- src/compile/server.rs
- src/compile/style.rs
- src/compile/tailwind.rs
- src/config/project.rs
- src/ext/exe.rs
- src/ext/mod.rs
- src/ext/util.rs
- src/lib.rs
- src/logger.rs
- src/service/notify.rs
- src/service/patch.rs
- src/service/reload.rs
- src/service/serve.rs
Running `cargo-audit` on this repo revealed that it depends directly on an unmaintained dependency: `ansi_term`. This PR removes that dependency. Fortunately, it just so happens that `clap`—which `cargo-leptos` already depends on—supports everything `cargo-leptos` was using `ansi_term` to do.
> Remove dep on ansi_term

- src/lib.rs
- src/main.rs
This allows me to link against the library without `panic`ing on twice initialised logging (I'm using tracing)
> refactor: Moved logging init into main.rs

- Cargo.lock
- Cargo.toml
- README.md
- src/command/new.rs
- src/compile/front.rs
- src/compile/tailwind.rs
- src/config/dotenvs.rs
- src/ext/exe.rs
- src/ext/tests.rs
- src/lib.rs
While working on the Tailwind v4 PR, I noticed that there were some things that are handled with separate binaries that have libraries that do the same thing. I took the liberty of switching to using those libraries. This might also make it easier to handle [the version issue I an into with the Tailwind v4 PR](https://github.com/leptos-rs/cargo-leptos/pull/428#issuecomment-2629199292).
Even though this PR says it has a lot of additions, almost all of them are from the lockfile. As far as actual source code is concerned, this allowed me to rip out a lot of now unnecessary code.
> Use libraries instead of locally installed binaries for Cargo Generate and Wasm Opt

- src/command/watch.rs
Closes: https://github.com/leptos-rs/cargo-leptos/issues/385
> fix: do not panic on interrupt channel for watch

- Cargo.lock
- Cargo.toml
- src/compile/change.rs
- src/service/notify.rs
This PR does:
- aggregates the change events from notify (every 100 ms) and then tries to send appropriate signals to build loops.
- prevents overloading the interrupt-based cycle, especially while modifying multiple files.
- makes the event loop more efficient.
> fix(watch): add debounce to notify

- src/command/watch.rs
Due to the cfg(debug_assertions) line here:
https://github.com/leptos-rs/leptos/blob/7c34b4a4a5daeb6bd340b0ccb684e9d2f616f306/leptos/src/into_view.rs#L110
Hot reloading does not work if you pass --release, as debug_assertions is off in release mode. This results in the relevant element tagging being missing from the HTML document and the hot reload node walker not walking any nodes.
This commit simply warns if a user passes --release and --hot-reload together to leptos watch to save time when a user encounters this issue.
I've put the text "warning:" before as it seems in this context the warning message is printed such that the first word is colorized, and without the text "warning:"
> fix: warn on watch with --release and --hot-reload

- examples/project/Cargo.lock
- examples/project/Cargo.toml
- examples/project/end2end/package-lock.json
- examples/project/end2end/package.json
- examples/project/src/app.rs
- examples/project/src/lib.rs
- examples/project/src/server.rs
Since 0.7.x has been stable for awhile, I think it makes sense to make the example for `cargo-leptos` use it.
> Update version of example to 0.7.x

- README.md
- src/config/project.rs
I brought this up in the Discord channel for `cargo-leptos`.
> Add documentation for some env vars/config options

- Cargo.lock
- Cargo.toml
Compiling cargo-leptos is broken in version v0.2.29 due to OpenSSL-related dependencies for the `aarch64-linux-unknown-musl` target. I've successfully compiled and verified functionality after applying this fix using the following docker image:
```docker
FROM public.ecr.aws/docker/library/alpine:latest
RUN apk update && \
apk add --no-cache \
bash \
git \
binaryen \
gcc \
g++ \
perl \
make \
npm \
curl
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup target add wasm32-unknown-unknown
...
```
The feature flag relies on the version pinned by carg-generate's dependencies and may be slightly older than the `openssl` crate.
> Fix `aarch64-linux-unknown-musl` by using vendored-openssl in cargo-generate

- src/ext/exe.rs
Update reference to the Sass GitHub repository based on https://github.com/sass-contrib/dart-sass-musl. This project has been merged into sass/dart-sass.
> chore: update Sass GitHub repository

- Cargo.lock
- src/compile/front.rs
- src/config/cli.rs
- src/ext/sync.rs
This helps me write Rust-powered developer scripts to have fine-grained control over cargo-leptos
> add: Cli.opts_mut

- src/command/new.rs
This PR closes #475.
It introduces two changes to the `cargo leptos new` subcommand:
- make either `--git` or `--path` required
- only allow `--branch` or `--tag` when `--git` is given
`cargo run -- new --init` > should ask you to provide either `--git` or `--path`
`cargo run -- new --branch b` > should ask you to provide `--git`
`cargo run -- new --tag t` > should ask you to provide `--git`
`cargo run -- new --git g --path p` > should error with message explaining that these args are exclusive
`cargo run -- new --git g --tag t --branch b` > should error with message explaining that these args are exclusive
> `cargo leptos new`: validate argument relationships

- Cargo.lock
- README.md
- src/compile/tests.rs
- src/config/project.rs
- src/config/snapshots/cargo_leptos__config__tests__workspace.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_bin_args_project2.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_in_subdir_project2.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_project1.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_project2.snap
- src/ext/exe.rs
Enabling this flag by default will offer significant compile time decreases and resolve some issues with debug symbols in dev mode. Also includes the flags `disable_erase_components` to stop this behavior and `always_enable_erase_components` to do this for both debug and prod
> Enable erase-components flag for debug mode

- Cargo.lock
- Cargo.toml
- src/compile/front.rs
- src/compile/server.rs
- src/config/project.rs
- src/service/serve.rs
I found the trick. #499 follow-up (I closed it and couldn't reopen it).
@benwis This PR works as expected. Please check it out. The only concern about his feature is that we should make sure the leptos examples will not run on debug builds as it will  be always on `erase_components` (Not related to this PR).
> fix: respect env rustflags, closes #496

- src/command/build.rs
In the muture we might also want to tackle the `add_hashes_to_site` case and the case of `build` vs `watch`, but for now I think this is sufficient, and having used this for a couple of months I haven't seen any problems.
Fixes #300
> Only return from build_proj after initially building all asset types. (Fixes #300)

- src/ext/exe.rs
I've seen this warning while working on #481 so I've decided to fix it while I have my editor open.
> remove unused import

- src/command/end2end.rs
Makes it behave like running the command in a shell would. Resolves #384
> fix: use `which` to run `end2end_cmd`

- Cargo.lock
- Cargo.toml
- src/compile/front.rs
- src/compile/hash.rs
- src/compile/tailwind.rs
- src/config/style.rs
- src/ext/exe.rs
- src/ext/eyre.rs
- src/ext/mod.rs
- src/lib.rs
- src/logger.rs
- src/main.rs
- The deprecated `color_eyre` has been replaced by core `eyre` crate.
- Upgraded `swc` and all deps
- Fixed clippy warnings
- Optimized the build release profile
> fix: removed deprecated color_eyre, upgraded swc and fixed clippy warnings

- src/service/notify.rs
This PR addresses the issue I opened [here](https://github.com/leptos-rs/cargo-leptos/issues/532)
> fix: `watch-additional-files` should now override `.gitignore`

- README.md
I believe "braces" always refer to { } characters. The name for [ ] is brackets (american english) or square brackets (british english). Using the square form here makes it unambiguous.
Source: https://en.wikipedia.org/wiki/Bracket
> Fix name for brackets in README.md

- README.md
- src/compile/front.rs
Without enabling this feature, trying to build a  Leptos project in release profile with strip enabled results in errors such as:
```    wasm-opt failed with:
[wasm-validator error in function 27] unexpected false: all used features should be allowed, on 
(i32.trunc_sat_f64_u
(local.get $8)
)
[wasm-validator error in function 27] unexpected false: all used features should be allowed, on 
(i32.trunc_sat_f64_u
(local.get $9)
)
[wasm-validator error in function 207] unexpected false: all used features should be allowed, on 
(i32.trunc_sat_f64_u
(local.get $4)
)
Fatal: error validating input
```
See https://github.com/rust-lang/rust/pull/137322
> Enable nontrapping-fptoint feature while invoking wasm-opt

- src/command/build.rs
- src/compile/tests.rs
- src/config/cli.rs
- src/config/project.rs
- src/config/snapshots/cargo_leptos__config__tests__workspace.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_bin_args_project2.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_in_subdir_project2.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_project1.snap
- src/config/snapshots/cargo_leptos__config__tests__workspace_project2.snap
- src/config/tests.rs
My PaaS prefers to have backends built in their own CI runners, but they're slow, so this lets me build the frontend in my own (faster) CI and then push the generated `target/site` along with the rest of the codebase into their CI.
> Implement --frontend-only and --backend-only options for build commands

- src/compile/tailwind.rs
If `content.transform` is not configured properly, Tailwind will not detect classes in `class:*` togglers and these classes will not be added to the build.
This only affects to TailwindCSS prior to v4.
> enh: add `class:` toggler transformer to default Tailwind config

- src/config/bin_package.rs
Previously, the binary extension (e.g., `.exe` for Windows) was chosen based on the host `target_os`, ignoring the configured `bin-target-triple`. This caused incorrect extensions for cross-compiled binaries.
> fix: Prioritize configured target triple over host target_os for binary extension selection

- src/compile/hash.rs
- src/wasm_split_tools/mod.rs
This supports the combination of lazy-loading and file-hashing by special-casing `__wasm_split.js`, which both refers to hashed files and is referred to by WASM binary files.
Needs to be used alongside https://github.com/leptos-rs/leptos/pull/4182.
Closes #552
> fix: support file hashing when using lazy loading

- Cargo.lock
- Cargo.toml
- README.md
- src/command/build.rs
- src/compile/front.rs
- src/compile/mod.rs
- src/config/cli.rs
- src/lib.rs
Since `cargo` now supports forwarding of shell completions of `cargo
<custom-cmd>` to `cargo-<custom-cmd>` for at least `bash` and `zsh`,
providing the backing completions seems useful.
They still have to be manually installed by the user, for `bash` that can be
done by either running `eval "$(cargo leptos completions bash)"` to enable the
completions for the *current* session and
```bash
cargo leptos completions bash > "${XDG_DATA_HOME:-"$HOME/.local/share}/bash-completion/completions/cargo-leptos"
```
to let `bash` lazily load the completions as soon as they are needed.
For `zsh` I'm not quite sure how they are working, but considering how other
projects manage autocompletions, describing the details of how the shells
completions work, might be not really necessary *anyway*.
> Add shell completions to `cargo-leptos`
