leptos-rs/cargo-leptos

src/service/serve.rs
Only copying the binary on windows. C.f. PR https://github.com/leptos-rs/cargo-leptos/pull/55
Closes #49, Closes #55
=> Only windows copying

README.md, src/compile/front.rs, src/compile/server.rs, src/config/bin_package.rs, src/config/cli.rs, src/config/lib_package.rs, src/config/mod.rs, src/config/profile.rs, src/config/project.rs, src/config/snapshots/cargo_leptos__config__tests__project.snap, src/config/snapshots/cargo_leptos__config__tests__workspace.snap, src/config/snapshots/cargo_leptos__config__tests__workspace_in_subdir_project2.snap, src/config/snapshots/cargo_leptos__config__tests__workspace_project1.snap, src/config/snapshots/cargo_leptos__config__tests__workspace_project2.snap
=> Add profile args

src/command/watch.rs
Fixes https://github.com/leptos-rs/cargo-leptos/issues/62.
When multiple file system updates occur close together in time, the first change (.rs file) may start a build process and the second (Tailwind css) may interrupt the build. The run_loop function was not checking if the
builds were interrupted and would clear the list of file changes. With the notification of the first file change now gone the rebuild process would not complete correctly. This change prevents the change list from being cleared if the builds have been interrupted by additional file system updates.
=> Handle interupts to build processes.

src/config/lib_package.rs, src/config/project.rs, src/config/snapshots/cargo_leptos__config__tests__project.snap, src/config/snapshots/cargo_leptos__config__tests__workspace.snap, src/config/snapshots/cargo_leptos__config__tests__workspace_in_subdir_project2.snap, src/config/snapshots/cargo_leptos__config__tests__workspace_project1.snap, src/config/snapshots/cargo_leptos__config__tests__workspace_project2.snap, src/ext/exe.rs, src/ext/tests.rs
Building first-party support for tailwindcss.
Added `bool` option for enabling tailwind support in `ProjectConfig`
Added tailwind to the `Exe` enum and `ExeMeta` struct
=> added tailwind option in project config and Exe enum

README.md, src/compile/server.rs, src/config/bin_package.rs, src/config/dotenvs.rs, src/config/project.rs
Fix issue where env vars are not properly overlayed + add bin-target-triple config.
=> Target triple

src/command/watch.rs, src/compile/front.rs, src/compile/server.rs, src/ext/mod.rs, src/ext/sync.rs, src/signal/product.rs
=> Fix for watch fail recompile after build error

src/command/build.rs, src/command/end2end.rs, src/command/serve.rs, src/command/watch.rs, src/signal/product.rs
=> Use ctrl-c handling for build, serve and end2end

src/config/project.rs
=> Check that server and reload ports are different

README.md, examples/project/Cargo.toml, examples/project/js/foo.js, examples/project/src/app/mod.rs, examples/project/src/lib.rs, src/compile/front.rs, src/config/project.rs, src/service/notify.rs, src/snapshots/cargo_leptos__tests__workspace_build.snap
Support for bindgen JS snippets including triggering rebuilds on JS file change.
Closes #85
=> JS Snippets

src/command/end2end.rs
https://github.com/leptos-rs/cargo-leptos/issues/90
This pr raises an error when the external test command returns anything other than 0. 
That allows for e.g. a ci pipeline to fail when there have been tests failing.
I am happily awaiting a review !
=> respect return code of external test command

src/service/reload.rs
=> chore: fix typo

Cargo.lock, Cargo.toml, src/command/watch.rs, src/compile/tests.rs, src/config/cli.rs, src/config/project.rs, src/config/snapshots/cargo_leptos__config__tests__project.snap, src/config/snapshots/cargo_leptos__config__tests__workspace.snap, src/config/snapshots/cargo_leptos__config__tests__workspace_in_subdir_project2.snap, src/config/snapshots/cargo_leptos__config__tests__workspace_project1.snap, src/config/snapshots/cargo_leptos__config__tests__workspace_project2.snap, src/config/tests.rs, src/service/mod.rs, src/service/notify.rs, src/service/patch.rs, src/service/reload.rs, src/signal/reload.rs
#89 has been squashed into f9140e8e611733feff869c0f6bf1ff37233be2ce because there were issues with conflicts (a rather clumsy approach, but it works...)
Use the command line feature `--hot-reload` to activate it.
=> Hot reload

src/ext/exe.rs
Grab the latest version of the tailwind cli
=> Update tailwind version to v.3.3.1

src/command/build.rs, src/command/test.rs
=> fix: cause error when a build or test fails

Cargo.lock, Cargo.toml
three module to remove
- "envy",
- "regex",
- "toml",
=> ran cargo machete

examples/project/Cargo.lock, examples/project/Cargo.toml
I saw this while reading the code, might as well fix upstream as I go.
=> chore examples/project Bumped cargo packages from 0.3 to 0.4

.github/workflows/release.yml, Cargo.lock
Updates the rust version to make it pass github actions.
=> Update Rust to make a release.

.github/workflows/release.yml
Not cool! 
At least we're running a good version always.
=> Cargo dist has changed the install script

src/compile/assets.rs
=> Remove hardcoded pkg dir

Cargo.lock, examples/project/Cargo.lock, examples/workspace/Cargo.lock
Hi,
This is just a `cargo update` for wasm-windgen [v0.2.88](https://github.com/rustwasm/wasm-bindgen/releases/tag/0.2.88), to fix an issue similar to #129
=> cargo update

src/ext/exe.rs
It adds nice things! It's non-breaking!
=> Bump default tailwind version

src/compile/style.rs
Refactor and clean up the style code a little bit. 
Draft because I need to test it.
=> Enable css bundling fix 238

Cargo.lock
=> Fix Cargo.lock for Nix users

Cargo.lock, Cargo.toml
So I am splitting up #274 into small parts.
Eventually that MEGA patch will be so small that the difficult to reason with aspect of the PR becomes workable.
=> Minor: Bump version numbers for Itertools and Brotli.

Cargo.lock, Cargo.toml
Over in #274 I am stripping off micro PRs, in order to reduce the complexity
=> Minor: Bumped flex_logger to 0.28.

Cargo.lock, Cargo.toml, src/command/build.rs, src/compile/front.rs, src/compile/tests.rs, src/config/cli.rs, src/config/dotenvs.rs, src/config/project.rs, src/config/snapshots/cargo_leptos__config__tests__workspace.snap, src/config/snapshots/cargo_leptos__config__tests__workspace_bin_args_project2.snap, src/config/snapshots/cargo_leptos__config__tests__workspace_in_subdir_project2.snap, src/config/snapshots/cargo_leptos__config__tests__workspace_project1.snap, src/config/snapshots/cargo_leptos__config__tests__workspace_project2.snap, src/config/tests.rs
Adds [swc](https://github.com/swc-project/swc) (Speedy Web Compiler) to minify javascript.
I have seen around 50% reduction in javascript filesize.
=> Feat: Minify javascript

Cargo.lock, Cargo.toml, examples/project/Cargo.lock, examples/project/Cargo.toml, examples/workspace/Cargo.lock, examples/workspace/project1/front/Cargo.toml, examples/workspace/project2/Cargo.toml, src/compile/front.rs, src/compile/hash.rs
=> Updated to wasm-bindgen 0.2.93

src/config/bin_package.rs
Issue: #364
Tests: Ran `cargo test`, all OK.
=> fix: better wasm target detection

src/config/bin_package.rs
fixes https://github.com/leptos-rs/cargo-leptos/issues/400
=> fix: read ignored bin_cargo_args from config file

Cargo.lock, Cargo.toml, src/service/notify.rs
=> fix: comprehensive ignore handling

.github/workflows/release.yml, dist-workspace.toml
@benwis, Let's try it out and see if it works.
=> fix(CI): build for musl

src/ext/exe.rs
=> fix(CI): extract downloaded binaries

dist-workspace.toml
Supersedes: #449  
Successful run: https://github.com/sabify/cargo-leptos/actions/runs/14006981060/job/39222115842
=> fix(CI): musl build

Cargo.lock, Cargo.toml
=> fix: upgrade zip to v3.0 and swc to v23.0 (closes #513)

src/wasm_split_tools/mod.rs
This is work done by @0xSerhii with comments by @fgardt in #545, and I just made some edits to reduce the size of the diff by minimizing changes. Integration tests are included as part of https://github.com/leptos-rs/leptos/pull/3988
Thanks so much for the fix. It is great to have additional eyes on this.
=> fix: correctly output split chunks (closes #546)

src/compile/hash.rs
Related to https://github.com/leptos-rs/leptos/issues/4322, but only when `hash-files = true`.
=> fix: add hashes for wasm-split manifest files when needed
